# Generated by Django 3.0.6 on 2020-05-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_hr_receptionist'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
