# Generated by Django 3.0.6 on 2020-05-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_invoice_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='paid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
